<h2>Page for blog</h2>


<table class="table table-striped">
    <thead>
    <tr>
        <th>id</th>
        <th>author_id</th>
        <th>title</th>
        <th>description</th>
        <th>content</th>
        <th>url_rewrite</th>
        <th>status</th>
        <th>create_at</th>
        <th>update_at</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($block->getBlog() as $blog): ?>
        <tr>
            <td><?php echo $blog->getId() ?></td>
            <td><?php echo $blog->getAuthorId() ?></td>
            <td><?php echo $blog->getTitle() ?></td>
            <td><?php echo $blog->getDescription() ?></td>
            <td><?php echo $blog->getContent() ?></td>
            <td><?php echo $blog->getUrlRewrite() ?></td>
            <td><?php echo $blog->getStatus() ?></td>
            <td><?php echo $blog->getCreateAt() ?></td>
            <td><?php echo $blog->getUpdateAt() ?></td>
        </tr>
    <?php endforeach; ?>

    </tbody>
</table>


