<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend">
        <span><?php /* @escapeNotVerified */echo __('Image Uploaded') ?></span>
    </legend>
    <?php if ($url = $block->getUrlAvatar()): ?>
        <div class="field">
            <img src="<?php echo $url ?>" alt="image" />
        </div>
        <div class="control">
            <label for="avatar" class="avatar-file-upload">
                <?php echo __('Upload new avatar'); ?>
            </label>
            <input type="file" id="avatar" name="avatar" value="" title="Your avatar" class="avatar validate-image" />
        </div>
    <?php endif;?>
</fieldset>

